# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
arch:
  - x64
  - x86
  - arm64
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
env:
  - JULIA_FFTW_PROVIDER=FFTW
  # - JULIA_FFTW_PROVIDER=MKL
  - JULIA_NUM_THREADS=2
matrix:
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - julia: nightly
      arch: arm64
  fast_finish: true
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FFTW"); Pkg.test("FFTW"; coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.dir("FFTW"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();
                                               Pkg.build("FFTW")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
